/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import javax.swing.JPanel;
import java.awt.Container;

/**
 *
 * @author Sam
 */
public class Main extends javax.swing.JFrame {

    
    /**
     * Creates new form Main
     */
    JPanel pnlCard, pnlTrangchu, pnlQLDiem, pnlQLGiangvien, pnlQLHocvien, pnlQLKhoahoc, pnlDangky;
    ArrayList<JPanel> listMenuLeft;
    CardLayout cards = new CardLayout();
    
    public Main() {
        initComponents();
        control();
        addEvents();
    }
    
    private void control(){
        
        pnlCard = new JPanel(cards);
        pnlTrangchu = new JPanel();
        pnlTrangchu.setBackground(Color.MAGENTA);
        pnlQLDiem = new JPanel();
        pnlQLGiangvien = new JPanel(); 
        pnlQLHocvien = new JPanel();
        pnlQLKhoahoc = new JPanel();
        pnlDangky = new JPanel();
        
        QLyHocVien hocvien = new QLyHocVien();
        hocvien.setVisible(true);
        pnlQLHocvien.add(hocvien);
        
        
        QLyGiangVien giangvien = new QLyGiangVien();
        giangvien.setVisible(true);
        pnlQLGiangvien.add(giangvien);
        
        
        QLyDiem diem = new QLyDiem();
        diem.setVisible(true);
        pnlQLDiem.add(diem);
        
        
        QLyKhoaHoc khoahoc = new QLyKhoaHoc();
        khoahoc.setVisible(true);
        pnlQLKhoahoc.add(khoahoc);
        
        DangKy dangky = new DangKy();
        dangky.setVisible(true);
        pnlDangky.add(dangky);
        
//        pnlCard.add(pnlTrangchu,"1");
        pnlCard.add(pnlQLHocvien,"1");
        pnlCard.add(pnlQLDiem,"2");
        pnlCard.add(pnlQLGiangvien,"3");
        pnlCard.add(pnlQLKhoahoc,"4");
        pnlCard.add(pnlDangky,"5");
        
        cards.show(pnlCard, "1");
        pnlView.add(pnlCard);
        
    }
    
    private void addEvents() {
        
        listMenuLeft = new ArrayList<>();
        
        listMenuLeft.add(pnlMenu_HV);
        listMenuLeft.add(pnlMenu_Diem);
        listMenuLeft.add(pnlMenu_GV);
        listMenuLeft.add(pnlMenu_KH);
        listMenuLeft.add(pnlMenu_DK);
//        listMenuLeft.add(pnlDangky);
        
        for( JPanel pnl : listMenuLeft)
            {
                pnl.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        
                        String cardname = "";
                        if(pnl == pnlMenu_HV){
                            cardname = "1";
                        }else if(pnl == pnlMenu_Diem){
                            cardname = "2";
                        }else if(pnl == pnlMenu_GV){
                            cardname = "3";
                        }else if(pnl == pnlMenu_KH){
                            cardname = "4";
                        }else if(pnl == pnlMenu_DK){
                            cardname = "5";
                        }
                        
                        cards.show(pnlCard, cardname);
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                        
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                       
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                        
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                        
                    }
                });
            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pnlMenu_HV = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlMenu_DK = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlMenu_KH = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlMenu_Diem = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlMenu_GV = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 20));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu_HV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenu_HV.setToolTipText("");
        pnlMenu_HV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Quản lý học viên");
        pnlMenu_HV.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 28));

        jPanel1.add(pnlMenu_HV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 150, 50));

        pnlMenu_DK.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenu_DK.setToolTipText("");
        pnlMenu_DK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Đăng ký");
        pnlMenu_DK.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 56, 29));

        jPanel1.add(pnlMenu_DK, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 150, 50));

        pnlMenu_KH.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenu_KH.setToolTipText("");
        pnlMenu_KH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Quản lý khóa học");
        pnlMenu_KH.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 28));

        jPanel1.add(pnlMenu_KH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 150, 50));

        pnlMenu_Diem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenu_Diem.setToolTipText("");
        pnlMenu_Diem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Quản lý điểm");
        pnlMenu_Diem.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, 28));

        jPanel1.add(pnlMenu_Diem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 150, 50));

        pnlMenu_GV.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenu_GV.setToolTipText("");
        pnlMenu_GV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Quản lý giảng viên");
        pnlMenu_GV.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 28));

        jPanel1.add(pnlMenu_GV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 150, 50));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 640));

        pnlView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        pnlView.setPreferredSize(new java.awt.Dimension(810, 560));
        pnlView.setLayout(new java.awt.CardLayout());
        jPanel2.add(pnlView, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 730, 620));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main a = new Main();
                a.setVisible(true);
                a.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel pnlMenu_DK;
    private javax.swing.JPanel pnlMenu_Diem;
    private javax.swing.JPanel pnlMenu_GV;
    private javax.swing.JPanel pnlMenu_HV;
    private javax.swing.JPanel pnlMenu_KH;
    private javax.swing.JPanel pnlView;
    // End of variables declaration//GEN-END:variables
}
